services:
  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    ports: ["8000:8000"]
    depends_on: [redis]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  worker:
    build: .
    command: celery -A musicmood worker -l info
    env_file: .env
    depends_on: [redis]
