# Generated by Django 5.2.6 on 2025-09-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('handle', models.SlugField(max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('mood_keys', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
